name: CD
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  release:
    types: [published]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    container: node:10.16.3
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install APT packages
        run: apt-get update && apt-get install jq zip -y
      - name: Cache Node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Install Node modules
        run: npm install
      - name: Build
        run: BUILD_NUMBER=$GITHUB_SHA npm run build
      - name: Pack
        run: .github/workflows/pack.sh
      - name: Persist package
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: package/
      - name: Persist public dir
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/
      - name: Test
        run: npm test
      - name: Deploy to Netlify
        run: BUILD_DIR=public .github/workflows/deploy_to_netlify.sh
        env:
          NETLIFY_KEY: ${{ secrets.NETLIFY_KEY }}
